knpu_oauth2_client:
    clients:
        github:
                  # must be "github" - it activates that type!
                  type: github
                  # add and configure client_id and client_secret in parameters.yml
                  client_id: 'f3caf63ded6042985a8d'
                  client_secret: 'a388366dbba9bfa2b8516300f524ebd18e971fce'
                  # a route name you'll create
                  redirect_route: github_callback
                  redirect_params: {}

                  # whether to check OAuth2 "state": defaults to true
                  # use_state: true

              # will create service: "knpu.oauth2.client.gitlab"
              # an instance of: KnpU\OAuth2ClientBundle\Client\Provider\GitlabClient
              # composer require omines/oauth2-gitlab
        # configure your clients as described here: https://github.com/knpuniversity/oauth2-client-bundle#configuration
